<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // @see https://github.com/datasets/country-codes/blob/master/data/country-codes.csv
        // @see https://tableconvert.com/
        //["Dial","ISO3166-1-Alpha-3","ISO3166-1-Alpha-2","ISO4217-currency_name","ISO4217-currency_alphabetic_code","ISO4217-currency_country_name","Continent","TLD","Languages","CLDR display name"]

        $countries = [
            [886,"TWN","TW","","","","AS",".tw","zh-TW,zh,nan,hak","Taiwan"],
            [93,"AFG","AF","Afghani","AFN","AFGHANISTAN","AS",".af","fa-AF,ps,uz-AF,tk","Afghanistan"],
            [355,"ALB","AL","Lek","ALL","ALBANIA","EU",".al","sq,el","Albania"],
            [213,"DZA","DZ","Algerian Dinar","DZD","ALGERIA","AF",".dz","ar-DZ","Algeria"],
            ["1-684","ASM","AS","US Dollar","USD","AMERICAN SAMOA","OC",".as","en-AS,sm,to","American Samoa"],
            [376,"AND","AD","Euro","EUR","ANDORRA","EU",".ad","ca","Andorra"],
            [244,"AGO","AO","Kwanza","AOA","ANGOLA","AF",".ao","pt-AO","Angola"],
            ["1-264","AIA","AI","East Caribbean Dollar","XCD","ANGUILLA","NA",".ai","en-AI","Anguilla"],
            [672,"ATA","AQ","No universal currency","","ANTARCTICA","AN",".aq","","Antarctica"],
            ["1-268","ATG","AG","East Caribbean Dollar","XCD","ANTIGUA AND BARBUDA","NA",".ag","en-AG","Antigua & Barbuda"],
            [54,"ARG","AR","Argentine Peso","ARS","ARGENTINA","SA",".ar","es-AR,en,it,de,fr,gn","Argentina"],
            [374,"ARM","AM","Armenian Dram","AMD","ARMENIA","AS",".am","hy","Armenia"],
            [297,"ABW","AW","Aruban Florin","AWG","ARUBA","NA",".aw","nl-AW,pap,es,en","Aruba"],
            [61,"AUS","AU","Australian Dollar","AUD","AUSTRALIA","OC",".au","en-AU","Australia"],
            [43,"AUT","AT","Euro","EUR","AUSTRIA","EU",".at","de-AT,hr,hu,sl","Austria"],
            [994,"AZE","AZ","Azerbaijan Manat","AZN","AZERBAIJAN","AS",".az","az,ru,hy","Azerbaijan"],
            ["1-242","BHS","BS","Bahamian Dollar","BSD","BAHAMAS","NA",".bs","en-BS","Bahamas"],
            [973,"BHR","BH","Bahraini Dinar","BHD","BAHRAIN","AS",".bh","ar-BH,en,fa,ur","Bahrain"],
            [880,"BGD","BD","Taka","BDT","BANGLADESH","AS",".bd","bn-BD,en","Bangladesh"],
            ["1-246","BRB","BB","Barbados Dollar","BBD","BARBADOS","NA",".bb","en-BB","Barbados"],
            [375,"BLR","BY","Belarusian Ruble","BYN","BELARUS","EU",".by","be,ru","Belarus"],
            [32,"BEL","BE","Euro","EUR","BELGIUM","EU",".be","nl-BE,fr-BE,de-BE","Belgium"],
            [501,"BLZ","BZ","Belize Dollar","BZD","BELIZE","NA",".bz","en-BZ,es","Belize"],
            [229,"BEN","BJ","CFA Franc BCEAO","XOF","BENIN","AF",".bj","fr-BJ","Benin"],
            ["1-441","BMU","BM","Bermudian Dollar","BMD","BERMUDA","NA",".bm","en-BM,pt","Bermuda"],
            [975,"BTN","BT","Indian Rupee,Ngultrum","INR,BTN","BHUTAN","AS",".bt","dz","Bhutan"],
            [591,"BOL","BO","Boliviano","BOB","BOLIVIA (PLURINATIONAL STATE OF)","SA",".bo","es-BO,qu,ay","Bolivia"],
            [599,"BES","BQ","US Dollar","USD","BONAIRE, SINT EUSTATIUS AND SABA","NA",".bq","nl,pap,en","Caribbean Netherlands"],
            [387,"BIH","BA","Convertible Mark","BAM","BOSNIA AND HERZEGOVINA","EU",".ba","bs,hr-BA,sr-BA","Bosnia"],
            [267,"BWA","BW","Pula","BWP","BOTSWANA","AF",".bw","en-BW,tn-BW","Botswana"],
            [47,"BVT","BV","Norwegian Krone","NOK","BOUVET ISLAND","AN",".bv","","Bouvet Island"],
            [55,"BRA","BR","Brazilian Real","BRL","BRAZIL","SA",".br","pt-BR,es,en,fr","Brazil"],
            [246,"IOT","IO","US Dollar","USD","BRITISH INDIAN OCEAN TERRITORY","AS",".io","en-IO","British Indian Ocean Territory"],
            ["1-284","VGB","VG","US Dollar","USD","VIRGIN ISLANDS (BRITISH)","NA",".vg","en-VG","British Virgin Islands"],
            [673,"BRN","BN","Brunei Dollar","BND","BRUNEI DARUSSALAM","AS",".bn","ms-BN,en-BN","Brunei"],
            [359,"BGR","BG","Bulgarian Lev","BGN","BULGARIA","EU",".bg","bg,tr-BG,rom","Bulgaria"],
            [226,"BFA","BF","CFA Franc BCEAO","XOF","BURKINA FASO","AF",".bf","fr-BF,mos","Burkina Faso"],
            [257,"BDI","BI","Burundi Franc","BIF","BURUNDI","AF",".bi","fr-BI,rn","Burundi"],
            [238,"CPV","CV","Cabo Verde Escudo","CVE","CABO VERDE","AF",".cv","pt-CV","Cape Verde"],
            [855,"KHM","KH","Riel","KHR","CAMBODIA","AS",".kh","km,fr,en","Cambodia"],
            [237,"CMR","CM","CFA Franc BEAC","XAF","CAMEROON","AF",".cm","en-CM,fr-CM","Cameroon"],
            [1,"CAN","CA","Canadian Dollar","CAD","CANADA","NA",".ca","en-CA,fr-CA,iu","Canada"],
            ["1-345","CYM","KY","Cayman Islands Dollar","KYD","CAYMAN ISLANDS","NA",".ky","en-KY","Cayman Islands"],
            [236,"CAF","CF","CFA Franc BEAC","XAF","CENTRAL AFRICAN REPUBLIC","AF",".cf","fr-CF,sg,ln,kg","Central African Republic"],
            [235,"TCD","TD","CFA Franc BEAC","XAF","CHAD","AF",".td","fr-TD,ar-TD,sre","Chad"],
            [56,"CHL","CL","Chilean Peso","CLP","CHILE","SA",".cl","es-CL","Chile"],
            [86,"CHN","CN","Yuan Renminbi","CNY","CHINA","AS",".cn","zh-CN,yue,wuu,dta,ug,za","China"],
            [852,"HKG","HK","Hong Kong Dollar","HKD","HONG KONG","AS",".hk","zh-HK,yue,zh,en","Hong Kong"],
            [853,"MAC","MO","Pataca","MOP","MACAO","AS",".mo","zh,zh-MO,pt","Macau"],
            [61,"CXR","CX","Australian Dollar","AUD","CHRISTMAS ISLAND","OC",".cx","en,zh,ms-CC","Christmas Island"],
            [61,"CCK","CC","Australian Dollar","AUD","COCOS (KEELING) ISLANDS","AS",".cc","ms-CC,en","Cocos (Keeling) Islands"],
            [57,"COL","CO","Colombian Peso","COP","COLOMBIA","SA",".co","es-CO","Colombia"],
            [269,"COM","KM","Comorian Franc","KMF","COMOROS","AF",".km","ar,fr-KM","Comoros"],
            [242,"COG","CG","CFA Franc BEAC","XAF","CONGO","AF",".cg","fr-CG,kg,ln-CG","Congo - Brazzaville"],
            [682,"COK","CK","New Zealand Dollar","NZD","COOK ISLANDS","OC",".ck","en-CK,mi","Cook Islands"],
            [506,"CRI","CR","Costa Rican Colon","CRC","COSTA RICA","NA",".cr","es-CR,en","Costa Rica"],
            [385,"HRV","HR","Kuna","HRK","CROATIA","EU",".hr","hr-HR,sr","Croatia"],
            [53,"CUB","CU","Cuban Peso,Peso Convertible","CUP,CUC","CUBA","NA",".cu","es-CU,pap","Cuba"],
            [599,"CUW","CW","Netherlands Antillean Guilder","ANG","CURAÇAO","NA",".cw","nl,pap","Curaçao"],
            [357,"CYP","CY","Euro","EUR","CYPRUS","EU",".cy","el-CY,tr-CY,en","Cyprus"],
            [420,"CZE","CZ","Czech Koruna","CZK","CZECHIA","EU",".cz","cs,sk","Czechia"],
            [225,"CIV","CI","CFA Franc BCEAO","XOF","CÔTE D'IVOIRE","AF",".ci","fr-CI","Côte d’Ivoire"],
            [850,"PRK","KP","North Korean Won","KPW","KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)","AS",".kp","ko-KP","North Korea"],
            [243,"COD","CD","Congolese Franc","CDF","CONGO (THE DEMOCRATIC REPUBLIC OF THE)","AF",".cd","fr-CD,ln,ktu,kg,sw,lua","Congo - Kinshasa"],
            [45,"DNK","DK","Danish Krone","DKK","DENMARK","EU",".dk","da-DK,en,fo,de-DK","Denmark"],
            [253,"DJI","DJ","Djibouti Franc","DJF","DJIBOUTI","AF",".dj","fr-DJ,ar,so-DJ,aa","Djibouti"],
            ["1-767","DMA","DM","East Caribbean Dollar","XCD","DOMINICA","NA",".dm","en-DM","Dominica"],
            ["1-809,1-829,1-849","DOM","DO","Dominican Peso","DOP","DOMINICAN REPUBLIC","NA",".do","es-DO","Dominican Republic"],
            [593,"ECU","EC","US Dollar","USD","ECUADOR","SA",".ec","es-EC","Ecuador"],
            [20,"EGY","EG","Egyptian Pound","EGP","EGYPT","AF",".eg","ar-EG,en,fr","Egypt"],
            [503,"SLV","SV","El Salvador Colon,US Dollar","SVC,USD","EL SALVADOR","NA",".sv","es-SV","El Salvador"],
            [240,"GNQ","GQ","CFA Franc BEAC","XAF","EQUATORIAL GUINEA","AF",".gq","es-GQ,fr","Equatorial Guinea"],
            [291,"ERI","ER","Nakfa","ERN","ERITREA","AF",".er","aa-ER,ar,tig,kun,ti-ER","Eritrea"],
            [372,"EST","EE","Euro","EUR","ESTONIA","EU",".ee","et,ru","Estonia"],
            [268,"SWZ","SZ","Lilangeni","SZL","ESWATINI","AF",".sz","en-SZ,ss-SZ","Eswatini"],
            [251,"ETH","ET","Ethiopian Birr","ETB","ETHIOPIA","AF",".et","am,en-ET,om-ET,ti-ET,so-ET,sid","Ethiopia"],
            [500,"FLK","FK","","","","SA",".fk","en-FK","Falkland Islands"],
            [298,"FRO","FO","Danish Krone","DKK","FAROE ISLANDS","EU",".fo","fo,da-FO","Faroe Islands"],
            [679,"FJI","FJ","Fiji Dollar","FJD","FIJI","OC",".fj","en-FJ,fj","Fiji"],
            [358,"FIN","FI","Euro","EUR","FINLAND","EU",".fi","fi-FI,sv-FI,smn","Finland"],
            [33,"FRA","FR","Euro","EUR","FRANCE","EU",".fr","fr-FR,frp,br,co,ca,eu,oc","France"],
            [594,"GUF","GF","Euro","EUR","FRENCH GUIANA","SA",".gf","fr-GF","French Guiana"],
            [689,"PYF","PF","CFP Franc","XPF","FRENCH POLYNESIA","OC",".pf","fr-PF,ty","French Polynesia"],
            [262,"ATF","TF","Euro","EUR","FRENCH SOUTHERN TERRITORIES","AN",".tf","fr","French Southern Territories"],
            [241,"GAB","GA","CFA Franc BEAC","XAF","GABON","AF",".ga","fr-GA","Gabon"],
            [220,"GMB","GM","Dalasi","GMD","GAMBIA","AF",".gm","en-GM,mnk,wof,wo,ff","Gambia"],
            [995,"GEO","GE","Lari","GEL","GEORGIA","AS",".ge","ka,ru,hy,az","Georgia"],
            [49,"DEU","DE","Euro","EUR","GERMANY","EU",".de","de","Germany"],
            [233,"GHA","GH","Ghana Cedi","GHS","GHANA","AF",".gh","en-GH,ak,ee,tw","Ghana"],
            [350,"GIB","GI","Gibraltar Pound","GIP","GIBRALTAR","EU",".gi","en-GI,es,it,pt","Gibraltar"],
            [30,"GRC","GR","Euro","EUR","GREECE","EU",".gr","el-GR,en,fr","Greece"],
            [299,"GRL","GL","Danish Krone","DKK","GREENLAND","NA",".gl","kl,da-GL,en","Greenland"],
            ["1-473","GRD","GD","East Caribbean Dollar","XCD","GRENADA","NA",".gd","en-GD","Grenada"],
            [590,"GLP","GP","Euro","EUR","GUADELOUPE","NA",".gp","fr-GP","Guadeloupe"],
            ["1-671","GUM","GU","US Dollar","USD","GUAM","OC",".gu","en-GU,ch-GU","Guam"],
            [502,"GTM","GT","Quetzal","GTQ","GUATEMALA","NA",".gt","es-GT","Guatemala"],
            [44,"GGY","GG","Pound Sterling","GBP","GUERNSEY","EU",".gg","en,nrf","Guernsey"],
            [224,"GIN","GN","Guinean Franc","GNF","GUINEA","AF",".gn","fr-GN","Guinea"],
            [245,"GNB","GW","CFA Franc BCEAO","XOF","GUINEA-BISSAU","AF",".gw","pt-GW,pov","Guinea-Bissau"],
            [592,"GUY","GY","Guyana Dollar","GYD","GUYANA","SA",".gy","en-GY","Guyana"],
            [509,"HTI","HT","Gourde,US Dollar","HTG,USD","HAITI","NA",".ht","ht,fr-HT","Haiti"],
            [672,"HMD","HM","Australian Dollar","AUD","HEARD ISLAND AND MCDONALD ISLANDS","AN",".hm","","Heard & McDonald Islands"],
            ["39-06","VAT","VA","Euro","EUR","HOLY SEE","EU",".va","la,it,fr","Vatican City"],
            [504,"HND","HN","Lempira","HNL","HONDURAS","NA",".hn","es-HN,cab,miq","Honduras"],
            [36,"HUN","HU","Forint","HUF","HUNGARY","EU",".hu","hu-HU","Hungary"],
            [354,"ISL","IS","Iceland Krona","ISK","ICELAND","EU",".is","is,en,de,da,sv,no","Iceland"],
            [91,"IND","IN","Indian Rupee","INR","INDIA","AS",".in","en-IN,hi,bn,te,mr,ta,ur,gu,kn,ml,or,pa,as,bh,sat,ks,ne,sd,kok,doi,mni,sit,sa,fr,lus,inc","India"],
            [62,"IDN","ID","Rupiah","IDR","INDONESIA","AS",".id","id,en,nl,jv","Indonesia"],
            [98,"IRN","IR","Iranian Rial","IRR","IRAN (ISLAMIC REPUBLIC OF)","AS",".ir","fa-IR,ku","Iran"],
            [964,"IRQ","IQ","Iraqi Dinar","IQD","IRAQ","AS",".iq","ar-IQ,ku,hy","Iraq"],
            [353,"IRL","IE","Euro","EUR","IRELAND","EU",".ie","en-IE,ga-IE","Ireland"],
            [44,"IMN","IM","Pound Sterling","GBP","ISLE OF MAN","EU",".im","en,gv","Isle of Man"],
            [972,"ISR","IL","New Israeli Sheqel","ILS","ISRAEL","AS",".il","he,ar-IL,en-IL,","Israel"],
            [39,"ITA","IT","Euro","EUR","ITALY","EU",".it","it-IT,de-IT,fr-IT,sc,ca,co,sl","Italy"],
            ["1-876","JAM","JM","Jamaican Dollar","JMD","JAMAICA","NA",".jm","en-JM","Jamaica"],
            [81,"JPN","JP","Yen","JPY","JAPAN","AS",".jp","ja","Japan"],
            [44,"JEY","JE","Pound Sterling","GBP","JERSEY","EU",".je","en,fr,nrf","Jersey"],
            [962,"JOR","JO","Jordanian Dinar","JOD","JORDAN","AS",".jo","ar-JO,en","Jordan"],
            [7,"KAZ","KZ","Tenge","KZT","KAZAKHSTAN","AS",".kz","kk,ru","Kazakhstan"],
            [254,"KEN","KE","Kenyan Shilling","KES","KENYA","AF",".ke","en-KE,sw-KE","Kenya"],
            [686,"KIR","KI","Australian Dollar","AUD","KIRIBATI","OC",".ki","en-KI,gil","Kiribati"],
            [965,"KWT","KW","Kuwaiti Dinar","KWD","KUWAIT","AS",".kw","ar-KW,en","Kuwait"],
            [996,"KGZ","KG","Som","KGS","KYRGYZSTAN","AS",".kg","ky,uz,ru","Kyrgyzstan"],
            [856,"LAO","LA","Lao Kip","LAK","LAO PEOPLE’S DEMOCRATIC REPUBLIC","AS",".la","lo,fr,en","Laos"],
            [371,"LVA","LV","Euro","EUR","LATVIA","EU",".lv","lv,ru,lt","Latvia"],
            [961,"LBN","LB","Lebanese Pound","LBP","LEBANON","AS",".lb","ar-LB,fr-LB,en,hy","Lebanon"],
            [266,"LSO","LS","Loti,Rand","LSL,ZAR","LESOTHO","AF",".ls","en-LS,st,zu,xh","Lesotho"],
            [231,"LBR","LR","Liberian Dollar","LRD","LIBERIA","AF",".lr","en-LR","Liberia"],
            [218,"LBY","LY","Libyan Dinar","LYD","LIBYA","AF",".ly","ar-LY,it,en","Libya"],
            [423,"LIE","LI","Swiss Franc","CHF","LIECHTENSTEIN","EU",".li","de-LI","Liechtenstein"],
            [370,"LTU","LT","Euro","EUR","LITHUANIA","EU",".lt","lt,ru,pl","Lithuania"],
            [352,"LUX","LU","Euro","EUR","LUXEMBOURG","EU",".lu","lb,de-LU,fr-LU","Luxembourg"],
            [261,"MDG","MG","Malagasy Ariary","MGA","MADAGASCAR","AF",".mg","fr-MG,mg","Madagascar"],
            [265,"MWI","MW","Malawi Kwacha","MWK","MALAWI","AF",".mw","ny,yao,tum,swk","Malawi"],
            [60,"MYS","MY","Malaysian Ringgit","MYR","MALAYSIA","AS",".my","ms-MY,en,zh,ta,te,ml,pa,th","Malaysia"],
            [960,"MDV","MV","Rufiyaa","MVR","MALDIVES","AS",".mv","dv,en","Maldives"],
            [223,"MLI","ML","CFA Franc BCEAO","XOF","MALI","AF",".ml","fr-ML,bm","Mali"],
            [356,"MLT","MT","Euro","EUR","MALTA","EU",".mt","mt,en-MT","Malta"],
            [692,"MHL","MH","US Dollar","USD","MARSHALL ISLANDS","OC",".mh","mh,en-MH","Marshall Islands"],
            [596,"MTQ","MQ","Euro","EUR","MARTINIQUE","NA",".mq","fr-MQ","Martinique"],
            [222,"MRT","MR","Ouguiya","MRU","MAURITANIA","AF",".mr","ar-MR,fuc,snk,fr,mey,wo","Mauritania"],
            [230,"MUS","MU","Mauritius Rupee","MUR","MAURITIUS","AF",".mu","en-MU,bho,fr","Mauritius"],
            [262,"MYT","YT","Euro","EUR","MAYOTTE","AF",".yt","fr-YT","Mayotte"],
            [52,"MEX","MX","Mexican Peso","MXN","MEXICO","NA",".mx","es-MX","Mexico"],
            [691,"FSM","FM","US Dollar","USD","MICRONESIA (FEDERATED STATES OF)","OC",".fm","en-FM,chk,pon,yap,kos,uli,woe,nkr,kpg","Micronesia"],
            [377,"MCO","MC","Euro","EUR","MONACO","EU",".mc","fr-MC,en,it","Monaco"],
            [976,"MNG","MN","Tugrik","MNT","MONGOLIA","AS",".mn","mn,ru","Mongolia"],
            [382,"MNE","ME","Euro","EUR","MONTENEGRO","EU",".me","sr,hu,bs,sq,hr,rom","Montenegro"],
            ["1-664","MSR","MS","East Caribbean Dollar","XCD","MONTSERRAT","NA",".ms","en-MS","Montserrat"],
            [212,"MAR","MA","Moroccan Dirham","MAD","MOROCCO","AF",".ma","ar-MA,ber,fr","Morocco"],
            [258,"MOZ","MZ","Mozambique Metical","MZN","MOZAMBIQUE","AF",".mz","pt-MZ,vmw","Mozambique"],
            [95,"MMR","MM","Kyat","MMK","MYANMAR","AS",".mm","my","Myanmar"],
            [264,"NAM","NA","Namibia Dollar,Rand","NAD,ZAR","NAMIBIA","AF",".na","en-NA,af,de,hz,naq","Namibia"],
            [674,"NRU","NR","Australian Dollar","AUD","NAURU","OC",".nr","na,en-NR","Nauru"],
            [977,"NPL","NP","Nepalese Rupee","NPR","NEPAL","AS",".np","ne,en","Nepal"],
            [31,"NLD","NL","Euro","EUR","NETHERLANDS","EU",".nl","nl-NL,fy-NL","Netherlands"],
            [687,"NCL","NC","CFP Franc","XPF","NEW CALEDONIA","OC",".nc","fr-NC","New Caledonia"],
            [64,"NZL","NZ","New Zealand Dollar","NZD","NEW ZEALAND","OC",".nz","en-NZ,mi","New Zealand"],
            [505,"NIC","NI","Cordoba Oro","NIO","NICARAGUA","NA",".ni","es-NI,en","Nicaragua"],
            [227,"NER","NE","CFA Franc BCEAO","XOF","NIGER","AF",".ne","fr-NE,ha,kr,dje","Niger"],
            [234,"NGA","NG","Naira","NGN","NIGERIA","AF",".ng","en-NG,ha,yo,ig,ff","Nigeria"],
            [683,"NIU","NU","New Zealand Dollar","NZD","NIUE","OC",".nu","niu,en-NU","Niue"],
            [672,"NFK","NF","Australian Dollar","AUD","NORFOLK ISLAND","OC",".nf","en-NF","Norfolk Island"],
            ["1-670","MNP","MP","US Dollar","USD","NORTHERN MARIANA ISLANDS","OC",".mp","fil,tl,zh,ch-MP,en-MP","Northern Mariana Islands"],
            [47,"NOR","NO","Norwegian Krone","NOK","NORWAY","EU",".no","no,nb,nn,se,fi","Norway"],
            [968,"OMN","OM","Rial Omani","OMR","OMAN","AS",".om","ar-OM,en,bal,ur","Oman"],
            [92,"PAK","PK","Pakistan Rupee","PKR","PAKISTAN","AS",".pk","ur-PK,en-PK,pa,sd,ps,brh","Pakistan"],
            [680,"PLW","PW","US Dollar","USD","PALAU","OC",".pw","pau,sov,en-PW,tox,ja,fil,zh","Palau"],
            [507,"PAN","PA","Balboa,US Dollar","PAB,USD","PANAMA","NA",".pa","es-PA,en","Panama"],
            [675,"PNG","PG","Kina","PGK","PAPUA NEW GUINEA","OC",".pg","en-PG,ho,meu,tpi","Papua New Guinea"],
            [595,"PRY","PY","Guarani","PYG","PARAGUAY","SA",".py","es-PY,gn","Paraguay"],
            [51,"PER","PE","Sol","PEN","PERU","SA",".pe","es-PE,qu,ay","Peru"],
            [63,"PHL","PH","Philippine Peso","PHP","PHILIPPINES","AS",".ph","tl,en-PH,fil,ceb,tgl,ilo,hil,war,pam,bik,bcl,pag,mrw,tsg,mdh,cbk,krj,sgd,msb,akl,ibg,yka,mta,abx","Philippines"],
            [870,"PCN","PN","New Zealand Dollar","NZD","PITCAIRN","OC",".pn","en-PN","Pitcairn Islands"],
            [48,"POL","PL","Zloty","PLN","POLAND","EU",".pl","pl","Poland"],
            [351,"PRT","PT","Euro","EUR","PORTUGAL","EU",".pt","pt-PT,mwl","Portugal"],
            [1,"PRI","PR","US Dollar","USD","PUERTO RICO","NA",".pr","en-PR,es-PR","Puerto Rico"],
            [974,"QAT","QA","Qatari Rial","QAR","QATAR","AS",".qa","ar-QA,es","Qatar"],
            [82,"KOR","KR","Won","KRW","KOREA (THE REPUBLIC OF)","AS",".kr","ko-KR,en","South Korea"],
            [373,"MDA","MD","Moldovan Leu","MDL","MOLDOVA (THE REPUBLIC OF)","EU",".md","ro,ru,gag,tr","Moldova"],
            [40,"ROU","RO","Romanian Leu","RON","ROMANIA","EU",".ro","ro,hu,rom","Romania"],
            [7,"RUS","RU","Russian Ruble","RUB","RUSSIAN FEDERATION","EU",".ru","ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv,mdf,chm,ba,inh,tut,kbd,krc,av,sah,nog","Russia"],
            [250,"RWA","RW","Rwanda Franc","RWF","RWANDA","AF",".rw","rw,en-RW,fr-RW,sw","Rwanda"],
            [262,"REU","RE","Euro","EUR","RÉUNION","AF",".re","fr-RE","Réunion"],
            [590,"BLM","BL","Euro","EUR","SAINT BARTHÉLEMY","NA",".gp","fr","St. Barthélemy"],
            [290,"SHN","SH","Saint Helena Pound","SHP","SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA","AF",".sh","en-SH","St. Helena"],
            ["1-869","KNA","KN","East Caribbean Dollar","XCD","SAINT KITTS AND NEVIS","NA",".kn","en-KN","St. Kitts & Nevis"],
            ["1-758","LCA","LC","East Caribbean Dollar","XCD","SAINT LUCIA","NA",".lc","en-LC","St. Lucia"],
            [590,"MAF","MF","Euro","EUR","SAINT MARTIN (FRENCH PART)","NA",".gp","fr","St. Martin"],
            [508,"SPM","PM","Euro","EUR","SAINT PIERRE AND MIQUELON","NA",".pm","fr-PM","St. Pierre & Miquelon"],
            ["1-784","VCT","VC","East Caribbean Dollar","XCD","SAINT VINCENT AND THE GRENADINES","NA",".vc","en-VC,fr","St. Vincent & Grenadines"],
            [685,"WSM","WS","Tala","WST","SAMOA","OC",".ws","sm,en-WS","Samoa"],
            [378,"SMR","SM","Euro","EUR","SAN MARINO","EU",".sm","it-SM","San Marino"],
            [239,"STP","ST","Dobra","STN","SAO TOME AND PRINCIPE","AF",".st","pt-ST","São Tomé & Príncipe"],
            [966,"SAU","SA","Saudi Riyal","SAR","SAUDI ARABIA","AS",".sa","ar-SA","Saudi Arabia"],
            [221,"SEN","SN","CFA Franc BCEAO","XOF","SENEGAL","AF",".sn","fr-SN,wo,fuc,mnk","Senegal"],
            [381,"SRB","RS","Serbian Dinar","RSD","SERBIA","EU",".rs","sr,hu,bs,rom","Serbia"],
            [248,"SYC","SC","Seychelles Rupee","SCR","SEYCHELLES","AF",".sc","en-SC,fr-SC","Seychelles"],
            [232,"SLE","SL","Leone","SLL","SIERRA LEONE","AF",".sl","en-SL,men,tem","Sierra Leone"],
            [65,"SGP","SG","Singapore Dollar","SGD","SINGAPORE","AS",".sg","cmn,en-SG,ms-SG,ta-SG,zh-SG","Singapore"],
            ["1-721","SXM","SX","Netherlands Antillean Guilder","ANG","SINT MAARTEN (DUTCH PART)","NA",".sx","nl,en","Sint Maarten"],
            [421,"SVK","SK","Euro","EUR","SLOVAKIA","EU",".sk","sk,hu","Slovakia"],
            [386,"SVN","SI","Euro","EUR","SLOVENIA","EU",".si","sl,sh","Slovenia"],
            [677,"SLB","SB","Solomon Islands Dollar","SBD","SOLOMON ISLANDS","OC",".sb","en-SB,tpi","Solomon Islands"],
            [252,"SOM","SO","Somali Shilling","SOS","SOMALIA","AF",".so","so-SO,ar-SO,it,en-SO","Somalia"],
            [27,"ZAF","ZA","Rand","ZAR","SOUTH AFRICA","AF",".za","zu,xh,af,nso,en-ZA,tn,st,ts,ss,ve,nr","South Africa"],
            [500,"SGS","GS","No universal currency","","SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS","AN",".gs","en","South Georgia & South Sandwich Islands"],
            [211,"SSD","SS","South Sudanese Pound","SSP","SOUTH SUDAN","AF","","en","South Sudan"],
            [34,"ESP","ES","Euro","EUR","SPAIN","EU",".es","es-ES,ca,gl,eu,oc","Spain"],
            [94,"LKA","LK","Sri Lanka Rupee","LKR","SRI LANKA","AS",".lk","si,ta,en","Sri Lanka"],
            [970,"PSE","PS","No universal currency","","PALESTINE, STATE OF","AS",".ps","ar-PS","Palestine"],
            [249,"SDN","SD","Sudanese Pound","SDG","SUDAN","AF",".sd","ar-SD,en,fia","Sudan"],
            [597,"SUR","SR","Surinam Dollar","SRD","SURINAME","SA",".sr","nl-SR,en,srn,hns,jv","Suriname"],
            [47,"SJM","SJ","Norwegian Krone","NOK","SVALBARD AND JAN MAYEN","EU",".sj","no,ru","Svalbard & Jan Mayen"],
            [46,"SWE","SE","Swedish Krona","SEK","SWEDEN","EU",".se","sv-SE,se,sma,fi-SE","Sweden"],
            [41,"CHE","CH","Swiss Franc","CHF","SWITZERLAND","EU",".ch","de-CH,fr-CH,it-CH,rm","Switzerland"],
            [963,"SYR","SY","Syrian Pound","SYP","SYRIAN ARAB REPUBLIC","AS",".sy","ar-SY,ku,hy,arc,fr,en","Syria"],
            [992,"TJK","TJ","Somoni","TJS","TAJIKISTAN","AS",".tj","tg,ru","Tajikistan"],
            [66,"THA","TH","Baht","THB","THAILAND","AS",".th","th,en","Thailand"],
            [389,"MKD","MK","Denar","MKD","MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)","EU",".mk","mk,sq,tr,rmm,sr","North Macedonia"],
            [670,"TLS","TL","US Dollar","USD","TIMOR-LESTE","OC",".tl","tet,pt-TL,id,en","Timor-Leste"],
            [228,"TGO","TG","CFA Franc BCEAO","XOF","TOGO","AF",".tg","fr-TG,ee,hna,kbp,dag,ha","Togo"],
            [690,"TKL","TK","New Zealand Dollar","NZD","TOKELAU","OC",".tk","tkl,en-TK","Tokelau"],
            [676,"TON","TO","Pa’anga","TOP","TONGA","OC",".to","to,en-TO","Tonga"],
            ["1-868","TTO","TT","Trinidad and Tobago Dollar","TTD","TRINIDAD AND TOBAGO","NA",".tt","en-TT,hns,fr,es,zh","Trinidad & Tobago"],
            [216,"TUN","TN","Tunisian Dinar","TND","TUNISIA","AF",".tn","ar-TN,fr","Tunisia"],
            [90,"TUR","TR","Turkish Lira","TRY","TURKEY","AS",".tr","tr-TR,ku,diq,az,av","Turkey"],
            [993,"TKM","TM","Turkmenistan New Manat","TMT","TURKMENISTAN","AS",".tm","tk,ru,uz","Turkmenistan"],
            ["1-649","TCA","TC","US Dollar","USD","TURKS AND CAICOS ISLANDS","NA",".tc","en-TC","Turks & Caicos Islands"],
            [688,"TUV","TV","Australian Dollar","AUD","TUVALU","OC",".tv","tvl,en,sm,gil","Tuvalu"],
            [256,"UGA","UG","Uganda Shilling","UGX","UGANDA","AF",".ug","en-UG,lg,sw,ar","Uganda"],
            [380,"UKR","UA","Hryvnia","UAH","UKRAINE","EU",".ua","uk,ru-UA,rom,pl,hu","Ukraine"],
            [971,"ARE","AE","UAE Dirham","AED","UNITED ARAB EMIRATES","AS",".ae","ar-AE,fa,en,hi,ur","United Arab Emirates"],
            [44,"GBR","GB","Pound Sterling","GBP","UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND","EU",".uk","en-GB,cy-GB,gd","UK"],
            [255,"TZA","TZ","Tanzanian Shilling","TZS","TANZANIA, UNITED REPUBLIC OF","AF",".tz","sw-TZ,en,ar","Tanzania"],
            ["","UMI","UM","US Dollar","USD","UNITED STATES MINOR OUTLYING ISLANDS","OC",".um","en-UM","U.S. Outlying Islands"],
            ["1-340","VIR","VI","US Dollar","USD","VIRGIN ISLANDS (U.S.)","NA",".vi","en-VI","U.S. Virgin Islands"],
            [1,"USA","US","US Dollar","USD","UNITED STATES OF AMERICA","NA",".us","en-US,es-US,haw,fr","US"],
            [598,"URY","UY","Peso Uruguayo","UYU","URUGUAY","SA",".uy","es-UY","Uruguay"],
            [998,"UZB","UZ","Uzbekistan Sum","UZS","UZBEKISTAN","AS",".uz","uz,ru,tg","Uzbekistan"],
            [678,"VUT","VU","Vatu","VUV","VANUATU","OC",".vu","bi,en-VU,fr-VU","Vanuatu"],
            [58,"VEN","VE","Bolívar","VES","VENEZUELA (BOLIVARIAN REPUBLIC OF)","SA",".ve","es-VE","Venezuela"],
            [84,"VNM","VN","Dong","VND","VIET NAM","AS",".vn","vi,en,fr,zh,km","Vietnam"],
            [681,"WLF","WF","CFP Franc","XPF","WALLIS AND FUTUNA","OC",".wf","wls,fud,fr-WF","Wallis & Futuna"],
            [212,"ESH","EH","Moroccan Dirham","MAD","WESTERN SAHARA","AF",".eh","ar,mey","Western Sahara"],
            [967,"YEM","YE","Yemeni Rial","YER","YEMEN","AS",".ye","ar-YE","Yemen"],
            [260,"ZMB","ZM","Zambian Kwacha","ZMW","ZAMBIA","AF",".zm","en-ZM,bem,loz,lun,lue,ny,toi","Zambia"],
            [263,"ZWE","ZW","Zimbabwe Dollar","ZWL","ZIMBABWE","AF",".zw","en-ZW,sn,nr,nd","Zimbabwe"],
            [358,"ALA","AX","Euro","EUR","ÅLAND ISLANDS","EU",".ax","sv-AX","Åland Islands"],
        ];

        foreach ($countries as $country) {
            $model = new Country();

            $dials = array_filter(explode(',', $country[0]));

            $dial = null;
            if ($dials) {
                $dial = explode('-', $dials[0])[0];
            }

            //$model->dial = $country[0];
            $model->dial = $dial;
            $model->dials = json_encode(explode(',', $country[0]));
            $model->alpha3 = $country[1];
            $model->alpha2 = $country[2];
            $model->currency_name = $country[3];
            $model->currency_alphabetic_code = $country[4];
            $model->currency_country_name = $country[5];
            $model->continent = $country[6];
            $model->tld = $country[7];
            $model->languages = json_encode(explode(',', $country[8]));
            $model->display_name = $country[9];
            $model->save();
        }
    }
}
